# Generated by Django 5.0.7 on 2024-08-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_transaction_good_condition_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
